Minor: Fix flaky test failure due to missing locations
I saw a flaky test failure in

```
  1) Datadog::Profiling::Collectors::CpuAndWallTimeWorker#start Process::Waiter crash regression tests can sample an instance of Process::Waiter without crashing
     Failure/Error:
       samples_from_pprof(encoded_profile)
         .reject { |it| it.locations.first.path == "Garbage Collection" }
         .reject { |it| it.labels.include?(:"profiler overhead") }

     NoMethodError:
       undefined method `path' for nil:NilClass
     # ./spec/datadog/profiling/collectors/cpu_and_wall_time_worker_spec.rb:1628:in `block in samples_from_pprof_without_gc_and_overhead'
     # ./spec/datadog/profiling/collectors/cpu_and_wall_time_worker_spec.rb:1628:in `reject'
     # ./spec/datadog/profiling/collectors/cpu_and_wall_time_worker_spec.rb:1628:in `samples_from_pprof_without_gc_and_overhead'
     # ./spec/datadog/profiling/collectors/cpu_and_wall_time_worker_spec.rb:1098:in `block (5 levels) in <top (required)>'
     # ./spec/support/synchronization_helpers.rb:97:in `block in try_wait_until'
     # ./spec/support/synchronization_helpers.rb:96:in `times'
     # ./spec/support/synchronization_helpers.rb:96:in `try_wait_until'
     # ./spec/datadog/profiling/collectors/cpu_and_wall_time_worker_spec.rb:1097:in `block (4 levels) in <top (required)>'
     # ./spec/spec_helper.rb:272:in `block (2 levels) in <top (required)>'
     # ./spec/spec_helper.rb:154:in `block (2 levels) in <top (required)>'
     # .rvm/gems/ruby-3.2.5/gems/webmock-3.25.1/lib/webmock/rspec.rb:39:in `block (2 levels) in <top (required)>'
     # .rvm/gems/ruby-3.2.5/gems/rspec-wait-0.0.10/lib/rspec/wait.rb:47:in `block (2 levels) in <top (required)>'
     # ./spec/support/execute_in_fork.rb:32:in `run'
```

that I couldn't reproduce, but it seems reasonable to
add here a safe navigation and let the original
spec fail if a sample isn't as expected.