Remove broken "Test unstable" GitHub action
**What does this PR do?**:

The "Test unstable" GitHub Action runs the dd-trace-rb CI with
ruby-head and jruby-head.

Because ruby-head and jruby-head aren't always rock solid, we've marked
these tests with "continue-on-error: true" which in practice means you
need to actually open them to know if they failed, because they get
always marked as succeeded.

Today, while looking into our CI config, I noticed these tests have
been broken for what looks like *months* (due to some refactoring
in our gemspec):

```
[!] There was an error parsing `Gemfile`:
[!] There was an error while loading `ddtrace.gemspec`: syntax error, unexpected ']', expecting `end' or dummy end - ...ERSION::MAXIMUM_RUBY_VERSION}"]
...                              ^
. Bundler cannot continue.

 #  from /home/runner/work/dd-trace-rb/dd-trace-rb/ddtrace.gemspec:10
 #  -------------------------------------------
 #    spec.version               = DDTrace::VERSION::STRING
 >                                  "< #{DDTrace::VERSION::MAXIMUM_RUBY_VERSION}"]
 #    spec.required_rubygems_version = '>= 2.0.0'
 #  -------------------------------------------
. Bundler cannot continue.

 #  from /home/runner/work/dd-trace-rb/dd-trace-rb/Gemfile:3
 #  -------------------------------------------
 #
 >  gemspec
 #
 #  -------------------------------------------
Error: The process '/home/runner/.rubies/ruby-head/bin/bundle' failed with exit code 14
```

(https://github.com/DataDog/dd-trace-rb/actions/runs/5890935813/job/15977021676)

Nobody seems to notice when they fail, and thus it really looks like
we're not getting any value at all.

Thus, I decided to open a PR to remove them for now.

**Motivation**:

As our CI gets more complex, we get little value from things that
need to be checked manually -- nowadays we have hundreds of
validations.

**Additional Notes**:

N/A

**How to test the change?**:

Validate that CI is still green, and this action no longer runs.