[PROF-5808] Add `ENFORCE_TYPE` as user-friendly alternative to `Check_Type`
While investigating #2151, I realized that `Check_Type`'s error message:
`TypeError: wrong argument type nil (expected String)` is very hard to
debug in functions that do many `Check_Type` verifications
(such as `_native_do_export`).

To fix this, I've created a new `ENFORCE_TYPE` helper which behaves
similarly, but generates error messages such as:

```
TypeError: wrong argument nil for 'pprof_file_name' (expected a RUBY_T_STRING)
at ../../../../ext/ddtrace_profiling_native_extension/http_transport.c:280:in `_native_do_export'
```

Hopefully this message will help us get to the bottom of the issue.

I've modified every other use of `Check_Type` in the profiling
native extension to use this new helper, in case we need to debug
similar issues in the future.

Issue #2151