[NO-TICKET] Fix Ruby 2.3 system tests by using Debian 11 bullseye as a base
**What does this PR do?**

This PR changes our Ruby 2.3 docker image to use Debian 11 "bullseye"
as a base instead of Debian 12 "buster".

In https://github.com/DataDog/dd-trace-rb/pull/3534 we updated this
image but this broke system-tests
(https://github.com/DataDog/dd-trace-rb/actions/runs/8346827939/job/22845592152)
because they use an old nokogiri version that fails to build on
modern systems (https://github.com/sparklemotion/nokogiri/issues/2105):

```
$ gem install nokogiri -v '= 1.10.10'

xml_document.c:495:14: error: conflicting types for 'canonicalize'; have 'VALUE(int,  VALUE *, VALUE)' {aka 'long unsigned int(int,  long unsigned int *, long unsigned int)'}
  495 | static VALUE canonicalize(int argc, VALUE* argv, VALUE self)
      |              ^~~~~~~~~~~~
In file included from /usr/include/features.h:489,
                 from /usr/include/x86_64-linux-gnu/bits/libc-header-start.h:33,
                 from /usr/include/stdlib.h:26,
                 from ./nokogiri.h:4,
                 from ./xml_document.h:4,
                 from xml_document.c:1:
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:370:1: note: previous declaration of 'canonicalize' with type 'int(double *, const double *)'
  370 | __MATHDECL_1 (int, canonicalize,, (_Mdouble_ *__cx, const _Mdouble_ *__x));
      | ^~~~~~~~~~~~
make: *** [Makefile:240: xml_document.o] Error 1

make failed, exit code 2

Gem files will remain installed in /usr/local/bundle/gems/nokogiri-1.10.10 for inspection.
Results logged to /usr/local/bundle/extensions/x86_64-linux/2.3.0/nokogiri-1.10.10/gem_make.out
```

Rather than fighting nokogiri or the system-tests app, let's instead
gently step back from Debian 12 to 11, which should still buy us plenty
of time until we deprecate Ruby 2.3.

**Motivation:**

Fix CI/system-tests for Ruby 2.3.

**Additional Notes:**

N/A

**How to test the change?**

I've locally built the image with

```bash
$ docker build . -f Dockerfile-2.3.8 -t some-testing-name
```

and confirmed that nokogiri sucessfully installs.