Add workaround for incorrect compiler warning
gcc version 10.2.1 20210110 (Debian 10.2.1-6), used on our Ruby 2.7
images at time of writing, was incorrectly triggering a warning on this
code, and since in CI we compile with `-Werror` (we turn warnings into
errors), this was breaking.

This is not the first time we've seen gcc tripping around structure
initializers, so I'm not entirely surprised.

Shuffling the code around a bit made the warning go away.

Full details:
```
compiling ../../../../ext/ddtrace_profiling_native_extension/collectors_thread_context.c
../../../../ext/ddtrace_profiling_native_extension/collectors_thread_context.c: In function 'trigger_sample_for_thread':
../../../../ext/ddtrace_profiling_native_extension/collectors_thread_context.c:661:5: error: missing initializer for field 'num' of 'ddog_prof_Label' [-Werror=missing-field-initializers]
  661 |     };
      |     ^
In file included from /usr/local/bundle/gems/libdatadog-2.0.0.1.0-x86_64-linux/vendor/libdatadog-2.0.0/x86_64-linux/libdatadog-x86_64-unknown-linux-gnu/lib/pkgconfig/../../include/datadog/profiling.h:12,
                 from ../../../../ext/ddtrace_profiling_native_extension/collectors_stack.h:3,
                 from ../../../../ext/ddtrace_profiling_native_extension/collectors_thread_context.c:5:
/usr/local/bundle/gems/libdatadog-2.0.0.1.0-x86_64-linux/vendor/libdatadog-2.0.0/x86_64-linux/libdatadog-x86_64-unknown-linux-gnu/lib/pkgconfig/../../include/datadog/common.h:389:11: note: 'num' declared here
  389 |   int64_t num;
      |           ^~~
cc1: all warnings being treated as errors
```