Ensure release loads the same files as development (#844)
During development, we load `ddtrace` by through `ddtrace.gemspec`, which in turn eager loads 'ddtrace/version'.

Users load this gem by requiring `lib/ddtrace.rb`.
We need to ensure that any files loaded in our gemspec are also loaded there.

This fixed the following issue:
```
NameError: uninitialized constant Datadog::Span::VERSION
from .../lib/ddtrace/span.rb:246:in `<class:Span>'
```