Prevent `action_controller` tracing when disabled
In environments where tracing is disabled, Datadog spits out a lot of
unnecessary error logs here, due to the instrumentation assuming that
there's an active trace to maintain.

This fix is in the same vein as #1943 and #1945.

```
E, [2022-05-17T22:15:02.337370 #2639] ERROR -- ddtrace: [ddtrace] (/home/circleci/tmp/vendor/bundle/ruby/3.1.0/gems/ddtrace-1.0.0/lib/datadog/tracing/contrib/action_pack/action_controller/instrumentation.rb:43:in `rescue in start_processing') undefined method `resource=' for nil:NilClass

              trace.resource = span.resource
                   ^^^^^^^^^^^
E, [2022-05-17T22:15:02.340414 #2639] ERROR -- ddtrace: [ddtrace] (/home/circleci/tmp/vendor/bundle/ruby/3.1.0/gems/ddtrace-1.0.0/lib/datadog/tracing/contrib/action_pack/action_controller/instrumentation.rb:79:in `rescue in finish_processing') undefined method `resource=' for nil:NilClass

                trace.resource = span.resource
                     ^^^^^^^^^^^
```