Fix semantic conflict in collectors_cpu_and_wall_time_worker.c
* The semantic conflict is between https://github.com/DataDog/dd-trace-rb/pull/6435 and https://github.com/DataDog/dd-trace-rb/pull/6377
* It failed to compile like:
  ext/datadog_profiling_native_extension/collectors_cpu_and_wall_time_worker.c:685:5: error: ‘during_sample_exit_rescue’ undeclared (first use in this function); did you mean ‘during_sample_exit_ensure’?
    685 |     during_sample_exit_rescue, (VALUE) state
        |     ^~~~~~~~~~~~~~~~~~~~~~~~~
        |     during_sample_exit_ensure